# Generated by Django 5.2.14 on 2026-05-06 19:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("kafka_topic", models.CharField(max_length=100)),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("service", models.CharField(max_length=50)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="audit_audit_event_t_04511c_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__0bff9a_idx",
                    ),
                    models.Index(
                        fields=["occurred_at"], name="audit_audit_occurre_b8cdc4_idx"
                    ),
                    models.Index(
                        fields=["kafka_topic"], name="audit_audit_kafka_t_8096d7_idx"
                    ),
                ],
            },
        ),
    ]
