# Generated by Django 5.2.14 on 2026-05-06 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditevent",
            name="audit_audit_event_t_04511c_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditevent",
            name="audit_audit_occurre_b8cdc4_idx",
        ),
    ]
