# Generated by Django 5.2.14 on 2026-05-10 13:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("aggregate_type", models.CharField(max_length=50)),
                ("aggregate_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("key", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "PENDING")),
                        fields=["status", "created_at"],
                        name="outbox_pending_idx",
                    )
                ],
            },
        ),
    ]
