apiVersion: 1

contactPoints:
  - orgId: 1
    name: default
    receivers:
      - uid: default-receiver
        type: webhook
        settings:
          url: http://host.docker.internal:9999/webhook
          httpMethod: POST
        disableResolveMessage: false
