# Generated by Django 5.2.14 on 2026-05-06 09:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claim_number", models.CharField(max_length=20, unique=True)),
                ("policy_id", models.UUIDField(editable=False)),
                ("claimant_name", models.CharField(max_length=255)),
                ("claimant_email", models.EmailField(max_length=254)),
                ("incident_date", models.DateField()),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("ACCIDENTE", "Accidente"),
                            ("ROBO", "Robo"),
                            ("INCENDIO", "Incendio"),
                            ("INUNDACION", "Inundación"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "estimated_damage",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FILED", "Filed"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="FILED",
                        max_length=20,
                    ),
                ),
                ("filed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-filed_at"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_claims_status"),
                    models.Index(fields=["policy_id"], name="idx_claims_policy_id"),
                    models.Index(fields=["filed_at"], name="idx_claims_filed_at"),
                    models.Index(
                        fields=["incident_type"], name="idx_claims_incident_type"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=50)),
                ("file_url", models.URLField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at"],
                "indexes": [
                    models.Index(
                        fields=["claim", "changed_at"], name="idx_history_claim_date"
                    )
                ],
            },
        ),
    ]
