# Generated by Django 5.2.14 on 2026-05-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimstatushistory",
            name="from_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
